### ISSUE TITLE
Add tests to sample applications

### ISSUE THREAD

**Issue by awayken** [ColdBox/coldbox-samples#7]
Given the importance of testing code, it would be nice if the sample applications came with tests (unit or BDD). In that way, the applications would better mirror the expectations of modern developers, and they would also show how best to test things like handlers and models in the ColdBox way.

**Comment by bdw429s** [comment]
This is a great idea Miles.  We would be happy to accept pull requests from the community to get tests stubbed out in the sample apps.

**Comment by awayken** [comment]
Touché, @bdw429s.

I'll keep this in the back of my mind. I'm just dipping my feet into ColdBox waters, so I'll probably wait until I have a better foundation in how the framework works.

**Comment by awayken** [comment]
@bdw429s I submitted pull request #8 with some practice tests for the Hello World app. Let me know if these work or not.

**Comment by bdw429s** [comment]
Hi @awayken I've been out for a week but we'll take a look at this.  Thanks!
